services:
  - type: web
    name: etherxvision-backend
    env: python
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: OCR_MAX_DIM
        value: 800
      - key: WORKERS
        value: 1
      - key: FLAGS_initial_cpu_memory_in_mb
        value: "32"
      - key: FLAGS_allocator_strategy
        value: "naive_best_fit"
      - key: OMP_NUM_THREADS
        value: "1"

  - type: web
    name: etherxvision-frontend
    env: static
    branch: main
    rootDir: ocr-frontend
    buildCommand: npm install && npm run build
    staticPublishPath: build
